name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo apt update && sudo apt install ninja-build liblua5.1-dev liblua5.2-dev libncursesw5-dev zlib1g-dev libxft-dev
    - name: make
      run: make dev

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: brew
      run: brew install pkg-config ninja
    - name: make
      run: make dev

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: pacman
      run: |
        pacman -S --noconfirm --needed make ninja mingw-w64-i686-gcc gcc mingw-w64-i686-nsis pkg-config zip
    - name: build
      run: |
        make windows

