name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  dev-release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo apt update && sudo apt install ninja-build mingw-w64 libz-mingw-w64-dev nsis
    - name: make
      run: make windows distr debian-distr
    - uses: hole19/git-tag-action@master
      env:
        TAG: dev
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: release
      uses: softprops/action-gh-release@latest
      with:
        name: Development build
        body: |
          Automatic release.
        files:
          wordgrinder-*.tar.xz
          bin/WordGrinder-*-setup.exe
        tag_name: dev
        fail_on_unmatched_files: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
