name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: sudo apt update && sudo apt install ninja-build mingw-w64
    - name: make
      run: make windows distr debian-distr
    - name: "Upload wordgrinder-0.8.tar.xz"
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: "https://uploads.github.com/repos/davidgiven/wordgrinder/releases/dev/assets{?name,label}"
        asset_path: wordgrinder-0.8.tar.xz
        asset_name: wordgrinder-0.8.tar.xz
        asset_content_type: application/zip
